// Mocks generated by Mockito 5.4.6 from annotations
// in sample_notes/test/features/notes/mocks/all_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:typed_data' as _i15;

import 'package:bloc/bloc.dart' as _i22;
import 'package:dartz/dartz.dart' as _i4;
import 'package:hive/hive.dart' as _i2;
import 'package:hive/src/box/default_compaction_strategy.dart' as _i14;
import 'package:hive/src/box/default_key_comparator.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:sample_notes/core/error/failures.dart' as _i18;
import 'package:sample_notes/features/notes/data/datasources/note_entry_local_data_source.dart'
    as _i17;
import 'package:sample_notes/features/notes/data/models/note_entry_model.dart'
    as _i3;
import 'package:sample_notes/features/notes/domain/dto/create_note_request.dart'
    as _i20;
import 'package:sample_notes/features/notes/domain/dto/update_note_request.dart'
    as _i21;
import 'package:sample_notes/features/notes/domain/entities/note_entry.dart'
    as _i19;
import 'package:sample_notes/features/notes/domain/repository/note_entry_repository.dart'
    as _i5;
import 'package:sample_notes/features/notes/domain/usecases/create_note_entry.dart'
    as _i8;
import 'package:sample_notes/features/notes/domain/usecases/delete_note_entry.dart'
    as _i9;
import 'package:sample_notes/features/notes/domain/usecases/get_all_note_entries.dart'
    as _i6;
import 'package:sample_notes/features/notes/domain/usecases/get_note_entry.dart'
    as _i7;
import 'package:sample_notes/features/notes/domain/usecases/update_note_entry.dart'
    as _i10;
import 'package:sample_notes/features/notes/presentation/bloc/notes_bloc.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBox_0<E1> extends _i1.SmartFake implements _i2.Box<E1> {
  _FakeBox_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLazyBox_1<E1> extends _i1.SmartFake implements _i2.LazyBox<E1> {
  _FakeLazyBox_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNoteEntryModel_2 extends _i1.SmartFake
    implements _i3.NoteEntryModel {
  _FakeNoteEntryModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNoteEntryRepository_4 extends _i1.SmartFake
    implements _i5.NoteEntryRepository {
  _FakeNoteEntryRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllNoteEntries_5 extends _i1.SmartFake
    implements _i6.GetAllNoteEntries {
  _FakeGetAllNoteEntries_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetNoteEntry_6 extends _i1.SmartFake implements _i7.GetNoteEntry {
  _FakeGetNoteEntry_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateNoteEntry_7 extends _i1.SmartFake
    implements _i8.CreateNoteEntry {
  _FakeCreateNoteEntry_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteNoteEntry_8 extends _i1.SmartFake
    implements _i9.DeleteNoteEntry {
  _FakeDeleteNoteEntry_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateNoteEntry_9 extends _i1.SmartFake
    implements _i10.UpdateNoteEntry {
  _FakeUpdateNoteEntry_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotesState_10 extends _i1.SmartFake implements _i11.NotesState {
  _FakeNotesState_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HiveInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveInterface extends _i1.Mock implements _i2.HiveInterface {
  MockHiveInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void init(
    String? path, {
    _i2.HiveStorageBackendPreference? backendPreference =
        _i2.HiveStorageBackendPreference.native,
  }) => super.noSuchMethod(
    Invocation.method(#init, [path], {#backendPreference: backendPreference}),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i2.Box<E>> openBox<E>(
    String? name, {
    _i2.HiveCipher? encryptionCipher,
    _i2.KeyComparator? keyComparator = _i13.defaultKeyComparator,
    _i2.CompactionStrategy? compactionStrategy = _i14.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    _i15.Uint8List? bytes,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #openBox,
              [name],
              {
                #encryptionCipher: encryptionCipher,
                #keyComparator: keyComparator,
                #compactionStrategy: compactionStrategy,
                #crashRecovery: crashRecovery,
                #path: path,
                #bytes: bytes,
                #collection: collection,
                #encryptionKey: encryptionKey,
              },
            ),
            returnValue: _i12.Future<_i2.Box<E>>.value(
              _FakeBox_0<E>(
                this,
                Invocation.method(
                  #openBox,
                  [name],
                  {
                    #encryptionCipher: encryptionCipher,
                    #keyComparator: keyComparator,
                    #compactionStrategy: compactionStrategy,
                    #crashRecovery: crashRecovery,
                    #path: path,
                    #bytes: bytes,
                    #collection: collection,
                    #encryptionKey: encryptionKey,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i2.Box<E>>);

  @override
  _i12.Future<_i2.LazyBox<E>> openLazyBox<E>(
    String? name, {
    _i2.HiveCipher? encryptionCipher,
    _i2.KeyComparator? keyComparator = _i13.defaultKeyComparator,
    _i2.CompactionStrategy? compactionStrategy = _i14.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #openLazyBox,
              [name],
              {
                #encryptionCipher: encryptionCipher,
                #keyComparator: keyComparator,
                #compactionStrategy: compactionStrategy,
                #crashRecovery: crashRecovery,
                #path: path,
                #collection: collection,
                #encryptionKey: encryptionKey,
              },
            ),
            returnValue: _i12.Future<_i2.LazyBox<E>>.value(
              _FakeLazyBox_1<E>(
                this,
                Invocation.method(
                  #openLazyBox,
                  [name],
                  {
                    #encryptionCipher: encryptionCipher,
                    #keyComparator: keyComparator,
                    #compactionStrategy: compactionStrategy,
                    #crashRecovery: crashRecovery,
                    #path: path,
                    #collection: collection,
                    #encryptionKey: encryptionKey,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i2.LazyBox<E>>);

  @override
  _i2.Box<E> box<E>(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#box, [name]),
            returnValue: _FakeBox_0<E>(this, Invocation.method(#box, [name])),
          )
          as _i2.Box<E>);

  @override
  _i2.LazyBox<E> lazyBox<E>(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#lazyBox, [name]),
            returnValue: _FakeLazyBox_1<E>(
              this,
              Invocation.method(#lazyBox, [name]),
            ),
          )
          as _i2.LazyBox<E>);

  @override
  bool isBoxOpen(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#isBoxOpen, [name]),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteBoxFromDisk(String? name, {String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBoxFromDisk, [name], {#path: path}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteFromDisk() =>
      (super.noSuchMethod(
            Invocation.method(#deleteFromDisk, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  List<int> generateSecureKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateSecureKey, []),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i12.Future<bool> boxExists(String? name, {String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#boxExists, [name], {#path: path}),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  void resetAdapters() => super.noSuchMethod(
    Invocation.method(#resetAdapters, []),
    returnValueForMissingStub: null,
  );

  @override
  void registerAdapter<T>(
    _i2.TypeAdapter<T>? adapter, {
    bool? internal = false,
    bool? override = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #registerAdapter,
      [adapter],
      {#internal: internal, #override: override},
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool isAdapterRegistered(int? typeId) =>
      (super.noSuchMethod(
            Invocation.method(#isAdapterRegistered, [typeId]),
            returnValue: false,
          )
          as bool);

  @override
  void ignoreTypeId<T>(int? typeId) => super.noSuchMethod(
    Invocation.method(#ignoreTypeId, [typeId]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i2.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values =>
      (super.noSuchMethod(Invocation.getter(#values), returnValue: <E>[])
          as Iterable<E>);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  bool get isOpen =>
      (super.noSuchMethod(Invocation.getter(#isOpen), returnValue: false)
          as bool);

  @override
  bool get lazy =>
      (super.noSuchMethod(Invocation.getter(#lazy), returnValue: false)
          as bool);

  @override
  Iterable<dynamic> get keys =>
      (super.noSuchMethod(Invocation.getter(#keys), returnValue: <dynamic>[])
          as Iterable<dynamic>);

  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);

  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);

  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false)
          as bool);

  @override
  Iterable<E> valuesBetween({dynamic startKey, dynamic endKey}) =>
      (super.noSuchMethod(
            Invocation.method(#valuesBetween, [], {
              #startKey: startKey,
              #endKey: endKey,
            }),
            returnValue: <E>[],
          )
          as Iterable<E>);

  @override
  E? getAt(int? index) =>
      (super.noSuchMethod(Invocation.method(#getAt, [index])) as E?);

  @override
  Map<dynamic, E> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <dynamic, E>{},
          )
          as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) =>
      super.noSuchMethod(Invocation.method(#keyAt, [index]));

  @override
  _i12.Stream<_i2.BoxEvent> watch({dynamic key}) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {#key: key}),
            returnValue: _i12.Stream<_i2.BoxEvent>.empty(),
          )
          as _i12.Stream<_i2.BoxEvent>);

  @override
  bool containsKey(dynamic key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Future<void> put(dynamic key, E? value) =>
      (super.noSuchMethod(
            Invocation.method(#put, [key, value]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> putAt(int? index, E? value) =>
      (super.noSuchMethod(
            Invocation.method(#putAt, [index, value]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> putAll(Map<dynamic, E>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#putAll, [entries]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<int> add(E? value) =>
      (super.noSuchMethod(
            Invocation.method(#add, [value]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<Iterable<int>> addAll(Iterable<E>? values) =>
      (super.noSuchMethod(
            Invocation.method(#addAll, [values]),
            returnValue: _i12.Future<Iterable<int>>.value(<int>[]),
          )
          as _i12.Future<Iterable<int>>);

  @override
  _i12.Future<void> delete(dynamic key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAt, [index]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteAll(Iterable<dynamic>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [keys]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> compact() =>
      (super.noSuchMethod(
            Invocation.method(#compact, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<int> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteFromDisk() =>
      (super.noSuchMethod(
            Invocation.method(#deleteFromDisk, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> flush() =>
      (super.noSuchMethod(
            Invocation.method(#flush, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [NoteEntryLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteEntryLocalDataSource extends _i1.Mock
    implements _i17.NoteEntryLocalDataSource {
  MockNoteEntryLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i3.NoteEntryModel>> getAllNoteEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNoteEntries, []),
            returnValue: _i12.Future<List<_i3.NoteEntryModel>>.value(
              <_i3.NoteEntryModel>[],
            ),
          )
          as _i12.Future<List<_i3.NoteEntryModel>>);

  @override
  _i12.Future<_i3.NoteEntryModel> getNoteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteEntry, [id]),
            returnValue: _i12.Future<_i3.NoteEntryModel>.value(
              _FakeNoteEntryModel_2(
                this,
                Invocation.method(#getNoteEntry, [id]),
              ),
            ),
          )
          as _i12.Future<_i3.NoteEntryModel>);

  @override
  _i12.Future<_i3.NoteEntryModel> createNoteEntry(_i3.NoteEntryModel? note) =>
      (super.noSuchMethod(
            Invocation.method(#createNoteEntry, [note]),
            returnValue: _i12.Future<_i3.NoteEntryModel>.value(
              _FakeNoteEntryModel_2(
                this,
                Invocation.method(#createNoteEntry, [note]),
              ),
            ),
          )
          as _i12.Future<_i3.NoteEntryModel>);

  @override
  _i12.Future<_i3.NoteEntryModel> updateNoteEntry(_i3.NoteEntryModel? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteEntry, [note]),
            returnValue: _i12.Future<_i3.NoteEntryModel>.value(
              _FakeNoteEntryModel_2(
                this,
                Invocation.method(#updateNoteEntry, [note]),
              ),
            ),
          )
          as _i12.Future<_i3.NoteEntryModel>);

  @override
  _i12.Future<void> deleteNoteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNoteEntry, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [NoteEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteEntryRepository extends _i1.Mock
    implements _i5.NoteEntryRepository {
  MockNoteEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i4.Either<_i18.Failure, List<_i19.NoteEntry>>>
  getAllNoteEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNoteEntries, []),
            returnValue:
                _i12.Future<
                  _i4.Either<_i18.Failure, List<_i19.NoteEntry>>
                >.value(
                  _FakeEither_3<_i18.Failure, List<_i19.NoteEntry>>(
                    this,
                    Invocation.method(#getAllNoteEntries, []),
                  ),
                ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, List<_i19.NoteEntry>>>);

  @override
  _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>> getNoteEntry(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteEntry, [id]),
            returnValue:
                _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>.value(
                  _FakeEither_3<_i18.Failure, _i19.NoteEntry>(
                    this,
                    Invocation.method(#getNoteEntry, [id]),
                  ),
                ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>);

  @override
  _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>> createNoteEntry(
    _i20.CreateNoteRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNoteEntry, [request]),
            returnValue:
                _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>.value(
                  _FakeEither_3<_i18.Failure, _i19.NoteEntry>(
                    this,
                    Invocation.method(#createNoteEntry, [request]),
                  ),
                ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>);

  @override
  _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>> updateNoteEntry(
    _i21.UpdateNoteRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteEntry, [request]),
            returnValue:
                _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>.value(
                  _FakeEither_3<_i18.Failure, _i19.NoteEntry>(
                    this,
                    Invocation.method(#updateNoteEntry, [request]),
                  ),
                ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>);

  @override
  _i12.Future<_i4.Either<_i18.Failure, void>> deleteNoteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNoteEntry, [id]),
            returnValue: _i12.Future<_i4.Either<_i18.Failure, void>>.value(
              _FakeEither_3<_i18.Failure, void>(
                this,
                Invocation.method(#deleteNoteEntry, [id]),
              ),
            ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, void>>);
}

/// A class which mocks [GetAllNoteEntries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllNoteEntries extends _i1.Mock implements _i6.GetAllNoteEntries {
  MockGetAllNoteEntries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.NoteEntryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteEntryRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.NoteEntryRepository);

  @override
  _i12.Future<_i4.Either<_i18.Failure, List<_i19.NoteEntry>>> call(
    _i6.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i12.Future<
                  _i4.Either<_i18.Failure, List<_i19.NoteEntry>>
                >.value(
                  _FakeEither_3<_i18.Failure, List<_i19.NoteEntry>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, List<_i19.NoteEntry>>>);
}

/// A class which mocks [GetNoteEntry].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNoteEntry extends _i1.Mock implements _i7.GetNoteEntry {
  MockGetNoteEntry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.NoteEntryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteEntryRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.NoteEntryRepository);

  @override
  _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue:
                _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>.value(
                  _FakeEither_3<_i18.Failure, _i19.NoteEntry>(
                    this,
                    Invocation.method(#call, [id]),
                  ),
                ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>);
}

/// A class which mocks [CreateNoteEntry].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateNoteEntry extends _i1.Mock implements _i8.CreateNoteEntry {
  MockCreateNoteEntry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.NoteEntryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteEntryRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.NoteEntryRepository);

  @override
  _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>> call(
    _i20.CreateNoteRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue:
                _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>.value(
                  _FakeEither_3<_i18.Failure, _i19.NoteEntry>(
                    this,
                    Invocation.method(#call, [request]),
                  ),
                ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>);
}

/// A class which mocks [DeleteNoteEntry].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteNoteEntry extends _i1.Mock implements _i9.DeleteNoteEntry {
  MockDeleteNoteEntry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.NoteEntryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteEntryRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.NoteEntryRepository);

  @override
  _i12.Future<_i4.Either<_i18.Failure, void>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i12.Future<_i4.Either<_i18.Failure, void>>.value(
              _FakeEither_3<_i18.Failure, void>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, void>>);
}

/// A class which mocks [UpdateNoteEntry].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateNoteEntry extends _i1.Mock implements _i10.UpdateNoteEntry {
  MockUpdateNoteEntry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.NoteEntryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteEntryRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.NoteEntryRepository);

  @override
  _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>> call(
    _i21.UpdateNoteRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue:
                _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>.value(
                  _FakeEither_3<_i18.Failure, _i19.NoteEntry>(
                    this,
                    Invocation.method(#call, [request]),
                  ),
                ),
          )
          as _i12.Future<_i4.Either<_i18.Failure, _i19.NoteEntry>>);
}

/// A class which mocks [NotesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesBloc extends _i1.Mock implements _i11.NotesBloc {
  MockNotesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetAllNoteEntries get getAllNoteEntries =>
      (super.noSuchMethod(
            Invocation.getter(#getAllNoteEntries),
            returnValue: _FakeGetAllNoteEntries_5(
              this,
              Invocation.getter(#getAllNoteEntries),
            ),
          )
          as _i6.GetAllNoteEntries);

  @override
  _i7.GetNoteEntry get getNoteEntry =>
      (super.noSuchMethod(
            Invocation.getter(#getNoteEntry),
            returnValue: _FakeGetNoteEntry_6(
              this,
              Invocation.getter(#getNoteEntry),
            ),
          )
          as _i7.GetNoteEntry);

  @override
  _i8.CreateNoteEntry get createNoteEntry =>
      (super.noSuchMethod(
            Invocation.getter(#createNoteEntry),
            returnValue: _FakeCreateNoteEntry_7(
              this,
              Invocation.getter(#createNoteEntry),
            ),
          )
          as _i8.CreateNoteEntry);

  @override
  _i9.DeleteNoteEntry get deleteNoteEntry =>
      (super.noSuchMethod(
            Invocation.getter(#deleteNoteEntry),
            returnValue: _FakeDeleteNoteEntry_8(
              this,
              Invocation.getter(#deleteNoteEntry),
            ),
          )
          as _i9.DeleteNoteEntry);

  @override
  _i10.UpdateNoteEntry get updateNoteEntry =>
      (super.noSuchMethod(
            Invocation.getter(#updateNoteEntry),
            returnValue: _FakeUpdateNoteEntry_9(
              this,
              Invocation.getter(#updateNoteEntry),
            ),
          )
          as _i10.UpdateNoteEntry);

  @override
  List<_i19.NoteEntry> get notes =>
      (super.noSuchMethod(
            Invocation.getter(#notes),
            returnValue: <_i19.NoteEntry>[],
          )
          as List<_i19.NoteEntry>);

  @override
  set notes(List<_i19.NoteEntry>? value) => super.noSuchMethod(
    Invocation.setter(#notes, value),
    returnValueForMissingStub: null,
  );

  @override
  _i11.NotesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNotesState_10(this, Invocation.getter(#state)),
          )
          as _i11.NotesState);

  @override
  _i12.Stream<_i11.NotesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i11.NotesState>.empty(),
          )
          as _i12.Stream<_i11.NotesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i11.NotesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i11.NotesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i11.NotesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i11.NotesEvent>(
    _i22.EventHandler<E, _i11.NotesState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i22.Transition<_i11.NotesEvent, _i11.NotesState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i11.NotesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void onChange(_i22.Change<_i11.NotesState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
