// Mocks generated by Mockito 5.4.6 from annotations
// in sample_notes/test/features/notes/mocks/note_entry_local_datasource_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sample_notes/features/notes/data/datasources/note_entry_local_data_source.dart'
    as _i3;
import 'package:sample_notes/features/notes/data/models/note_entry_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNoteEntryModel_0 extends _i1.SmartFake
    implements _i2.NoteEntryModel {
  _FakeNoteEntryModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoteEntryLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteEntryLocalDataSource extends _i1.Mock
    implements _i3.NoteEntryLocalDataSource {
  MockNoteEntryLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.NoteEntryModel>> getAllNoteEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNoteEntries, []),
            returnValue: _i4.Future<List<_i2.NoteEntryModel>>.value(
              <_i2.NoteEntryModel>[],
            ),
          )
          as _i4.Future<List<_i2.NoteEntryModel>>);

  @override
  _i4.Future<_i2.NoteEntryModel> getNoteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteEntry, [id]),
            returnValue: _i4.Future<_i2.NoteEntryModel>.value(
              _FakeNoteEntryModel_0(
                this,
                Invocation.method(#getNoteEntry, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.NoteEntryModel>);

  @override
  _i4.Future<_i2.NoteEntryModel> createNoteEntry(_i2.NoteEntryModel? note) =>
      (super.noSuchMethod(
            Invocation.method(#createNoteEntry, [note]),
            returnValue: _i4.Future<_i2.NoteEntryModel>.value(
              _FakeNoteEntryModel_0(
                this,
                Invocation.method(#createNoteEntry, [note]),
              ),
            ),
          )
          as _i4.Future<_i2.NoteEntryModel>);

  @override
  _i4.Future<_i2.NoteEntryModel> updateNoteEntry(_i2.NoteEntryModel? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteEntry, [note]),
            returnValue: _i4.Future<_i2.NoteEntryModel>.value(
              _FakeNoteEntryModel_0(
                this,
                Invocation.method(#updateNoteEntry, [note]),
              ),
            ),
          )
          as _i4.Future<_i2.NoteEntryModel>);

  @override
  _i4.Future<void> deleteNoteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNoteEntry, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
