// Mocks generated by Mockito 5.4.6 from annotations
// in sample_notes/test/mocks/note_entry_repository_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sample_notes/core/error/failures.dart' as _i5;
import 'package:sample_notes/features/notes/domain/entities/note_entry.dart'
    as _i6;
import 'package:sample_notes/features/notes/domain/repository/note_entry_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoteEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteEntryRepository extends _i1.Mock
    implements _i3.NoteEntryRepository {
  MockNoteEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.NoteEntry>>>
  getAllNoteEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNoteEntries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.NoteEntry>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.NoteEntry>>(
                    this,
                    Invocation.method(#getAllNoteEntries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.NoteEntry>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.NoteEntry>> getNoteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteEntry, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.NoteEntry>>.value(
                  _FakeEither_0<_i5.Failure, _i6.NoteEntry>(
                    this,
                    Invocation.method(#getNoteEntry, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.NoteEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.NoteEntry>> createNoteEntry(
    _i6.NoteEntry? note,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNoteEntry, [note]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.NoteEntry>>.value(
                  _FakeEither_0<_i5.Failure, _i6.NoteEntry>(
                    this,
                    Invocation.method(#createNoteEntry, [note]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.NoteEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.NoteEntry>> updateNoteEntry(
    _i6.NoteEntry? note,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteEntry, [note]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.NoteEntry>>.value(
                  _FakeEither_0<_i5.Failure, _i6.NoteEntry>(
                    this,
                    Invocation.method(#updateNoteEntry, [note]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.NoteEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteNoteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNoteEntry, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteNoteEntry, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
